http:
  address: "${BENTHOS_HOST}"
  read_timeout: 5s
  root_path: /benthos
  debug_endpoints: false
input:
  type: nats_stream
  nats_stream:
    ack_wait: 30s
    batching:
      byte_size: 0
      condition:
        type: static
        static: false
      count: 1
      period: ""
      processors: []
    client_id: otf_reader_benthos_maps
    cluster_id: test-cluster
    durable_name: #benthos_offset
    max_inflight: 1024
    queue: #benthos_queue
    start_from_oldest: true
    subject: otf.maps.align
    unsubscribe_on_close: false
    urls:
      - nats://127.0.0.1:4222
buffer:
  type: none
  none: {}
pipeline:
  processors:
    - type: noop
  threads: 1
output:
  type: files
  files:
    path: ./msgs/${!count("files")}-${!timestamp_unix_nano()}.json
resources:
  caches: {}
  conditions: {}
  inputs: {}
  outputs: {}
  processors: {}
  rate_limits: {}
logger:
  prefix: benthos
  level: INFO
  add_timestamp: true
  json_format: true
  static_fields:
    '@service': benthos
metrics:
  type: http_server
  http_server:
    prefix: benthos
tracer:
  type: none
  none: {}
shutdown_timeout: 20s

